### ISSUE TITLE
Script fails parsing csv files

### ISSUE THREAD

**Issue by juosukai** [nmcspadden/PrinterGenerator#5]
I got the following error when using the script:

```
$ ./print_generator.py --csv paf_printers.csv 
Traceback (most recent call last):
  File "./print_generator.py", line 46, in <module>
    theOptionString = getOptionsString(row[6].split(" "))
  File "./print_generator.py", line 13, in getOptionsString
    for option in optionList.split(" "):
AttributeError: 'list' object has no attribute 'split'
```

The CSV was fine:

https://gist.github.com/anonymous/9ee79c76768ddd29c448

People wiser than me looked at the code, and provided the following bandaid:

https://gist.github.com/arubdesu/120a83a10025695f3be9

With the following comments:

```
allister [4:03 PM] 
insert a newline at line 13

allister [4:03 PM] 
use proper indentation, then

allister [4:03 PM]
optionList = str(optionList)

allister [4:04 PM] 
he’s not validating what type is passed, it should really be a try/except and in case of exception convert to string, which still may end up with garbage data

allister [4:04 PM]
not that I understand everything that went into this
```

Hopefully this will help you figure out what happened.

**Comment by nmcspadden** [comment]
This should be resolved with https://github.com/nmcspadden/PrinterGenerator/commit/898447d7f06775f7da648f9172087e57f19a8d29.
